apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
data:
  db-username: Y29wLWt1YmVybmV0ZXMtdXNlcg== # cop-kubernetes-user
  db-password: Y29wLWt1YmVybmV0ZXMxMjM0NTY= # cop-kubernetes123456