apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  selector:
    name: backend
    tier: backend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: http