apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: cop-kubernetes
spec:
  selector:
    name: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 30001