apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongodb-service
  namespace: cop-kubernetes
spec:
  ports:
  - name: "http"
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    service: mongo