apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: database
spec:
  selector:
    name: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None